blank_issues_enabled: false
contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/komikku-app/komikku/issues/
    about: Issues and requests about the app itself should be opened in Komikku's repository instead
  - name: 📦 Extension list
    url: https://warpdotsys.github.io/extensions
    about: List of all available extensions with download links
  - name: 🖥️ Komikku website
    url: https://komikku-app.github.io/docs/guides/troubleshooting/
    about: Guides, troubleshooting, and answers to common questions
